---
# Ansible Inventory untuk Development

all:
  children:
    test-t2:
      hosts:
        test-t2:
          # Connection Configuration
          ansible_host: 10.212.13.50
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          
      vars:
        # Network Configuration
        ip_addr: 127.0.0.1
        ip_subnet: 172.99.0.0/24
        
        # Docker Network IPs
        ip_nginx: 172.99.0.2
        ip_frontend: 172.99.0.3
        ip_backend: 172.99.0.4
        ip_fluentbit: 172.99.0.5
        ip_opensearch_node1: 172.99.0.6
        ip_opensearch_node2: 172.99.0.7
        ip_opensearch_dashboard: 172.99.0.8
        
        # Service Ports
        port_backend: 8080
        port_frontend: 3000
        opensearch_port: 9200
        opensearch_dashboard_port: 5601
        
        # OpenSearch Configuration
        opensearch_image: opensearchproject/opensearch
        opensearch_version: latest
        opensearch_host: 10.212.13.50
        opensearch_username: admin
        opensearch_password: d3l4p4Nk@r4kt3er
        opensearch_initial_admin_password: d3l4p4Nk@r4kt3er
        opensearch_cluster_name: opensearch-cluster
        
        opensearch_dashboard_image: opensearchproject/opensearch-dashboards
        opensearch_dashboard_version: latest
        
        # Nginx Configuration
        nginx_image: nginx
        nginx_version: latest
        nginx_host: 10.212.13.50
        
        # Application Images
        backend_image: docker.io/hiage/backend
        backend_version: development
        frontend_image: docker.io/hiage/frontend
        frontend_version: development
        
        # FluentBit Configuration
        fluentbit_image: docker.io/hiage/fluent-bit
        fluentbit_version: 4.0.5
        fluentbit_storage_path: /fluent-bit/storage
        
        # Services Version Name
        services_version: development
        
  vars:
    # Global Ansible Configuration
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: yes
    ansible_become_method: sudo
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'