---
# Tasks for installing Docker Python modules in a virtual environment

- name: Install python3-venv package
  apt:
    name: python3-venv
    state: present
  when: ansible_os_family == "Debian"

- name: Create virtual environment directory
  file:
    path: /opt/ansible_venv
    state: directory
    mode: '0755'

- name: Set up Python virtual environment
  command: python3 -m venv /opt/ansible_venv
  args:
    creates: /opt/ansible_venv/bin/activate

- name: Install Docker Python modules in virtual environment
  pip:
    name:
      - docker
      - docker-compose
    state: present
    virtualenv: /opt/ansible_venv
    virtualenv_command: python3 -m venv

- name: Create symlink to Python in virtual environment
  file:
    src: /opt/ansible_venv/bin/python
    dest: /usr/bin/python3
    state: link