---
# Tasks for Docker installation and configuration

- name: Add Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  when: ansible_user is defined

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.39.1/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
    # force: yes # update versi
  when: ansible_system == "Linux"

- name: Check Docker version
  command: docker --version
  register: docker_version
  changed_when: false

- name: Display Docker version
  debug:
    var: docker_version.stdout
    
# - name: Include Docker Python installation tasks
#   include_tasks: install_docker_python.yml